### ISSUE TITLE
[Feature] Can you make an option in save() to check the file exists or not in the path? 

### ISSUE THREAD

**Issue by rubanraj54** [x011/dload#1]
First of all, thanks for this awesome library.

Could you please make an option like this?

`def save(url, path="",replace_file=False):`

Thanks,
Ruby.

**Comment by x011** [comment]
Hi @rubanraj54, it will be added on the next release.

**Comment by x011** [comment]
Your request was included on version 0.4 - https://pypi.org/project/dload/
